### ISSUE TITLE
Wrong sorting order for NULL values when showing Sub Totals

### ISSUE THREAD

**Issue by IvoMoor** [rpbouman/huey#247] opened 2024-11-19 14:20 UTC
Null values are shown after the 'Total' column in case subtotals are activated.
Can be resolved by adding " ASC NULLS FIRST" in the Order By section

**Comment by rpbouman** [comment] 2024-11-19 14:36
If there are NULLs, then those rows might get sorted after the total row.
This should be fixed in the axis queries, possibly by adding NULLS FIRST, or possibly by including the grouping key into the ORDER BY list.

**Comment by rpbouman** [comment] 2024-11-25 03:35
Reopening because the current implementation also has issues.
![image](https://github.com/user-attachments/assets/a5e9933d-2c74-41ee-8b95-9e625ce38222)

**Comment by rpbouman** [comment] 2024-11-25 11:11
So the problem is essentially that whether NULLs are sorted first, and the desired position of the totals rows are functionally speaking independent things. But in SQL, they are intertwined, because totals rows happen to produce NULL values for the grouped columns. 

Things get interesting when 
- there are 'normal' NULL values in the data, 
- when we want to have the NULLs sorted in a way that disagrees with where we want the totals to appear.

To make these things work completely independently, we need an order by like this:

```
ORDER BY 
,right("__huey_grouping_id"::BIT::VARCHAR,3)::BIT & bitstring('100',3) 
,CAST( YEAR( "__huey_data_foundation"."request_datetime" ) AS INT) NULLS FIRST
,right("__huey_grouping_id"::BIT::VARCHAR,3)::BIT & bitstring('010',3) 
,CAST( MONTH( "__huey_data_foundation"."request_datetime" ) AS UTINYINT) NULLS FIRST
,right("__huey_grouping_id"::BIT::VARCHAR, 3)::BIT & bitstring('001',3) 
,CAST( DAYOFMONTH( "__huey_data_foundation"."request_datetime" ) AS UTINYINT) NULLS FIRST
```

For the normal columns, we can use NULLS FIRST | LAST to control how NULL values get sorted,
and for the group expressions we can use ASC | DESC to control whether totals should appear at the top or at the bottom

**Comment by rpbouman** [comment] 2024-11-29 00:36
![image](https://github.com/user-attachments/assets/489ccc37-fb2b-4731-888a-1e8dff533ffd)

**Closed** 2024-11-29 14:24 UTC
Labels: bug
